on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Run Luacheck
        uses: lunarmodules/luacheck@cc089e3f65acdd1ef8716cc73a3eca24a6b845e4 # v1
        with:
          args: >
            --read-globals
            LoGetPlayerPlaneId
            LoGetSelfData
            LuaExportActivityNextEvent
            LuaExportBeforeNextFrame
            lastPlayerPlaneId
            log
            --globals
            LuaExportActivityNextEvent
            lastPlayerPlaneId
            -- .
      - name: Lint Markdown Files
        uses: DavidAnson/markdownlint-cli2-action@21c1be1b93ad9ed58fa840aacc3f279cde2a72ff #v24
        with:
          globs: '**/*.md'
